from __future__ import annotations

from enum import Enum


class ReasonCode(str, Enum):
    UNAUTHORIZED_SUBSTITUTION = "UNAUTHORIZED_SUBSTITUTION"
    LOW_IC = "LOW_IC"
    HIGH_IMPLICATION_BREAK = "HIGH_IMPLICATION_BREAK"
    MISSING_NEEDED_INFO = "MISSING_NEEDED_INFO"
    IRREVERSIBLE_UNVERIFIED = "IRREVERSIBLE_UNVERIFIED"
    LOW_CONFIDENCE = "LOW_CONFIDENCE"
    HIGH_RISK = "HIGH_RISK"
    AUTHORITY_CONFLICT = "AUTHORITY_CONFLICT"
    PLANNING_SIGNAL_WEAK = "PLANNING_SIGNAL_WEAK"
    CONTRADICTION_REPAIR_PENDING = "CONTRADICTION_REPAIR_PENDING"
    POLICY_REQUIRED_SUBSTITUTION = "POLICY_REQUIRED_SUBSTITUTION"
    BLOCKED_BY_RUNTIME_POLICY = "BLOCKED_BY_RUNTIME_POLICY"


ALL_REASON_CODES = tuple(code.value for code in ReasonCode)


def is_known_reason_code(code: str) -> bool:
    return code in ALL_REASON_CODES
